// Curated family route for children around six years old. Ride restrictions
// come from the linked official Energylandia pages. Coordinates are entrances
// or useful ride centroids from the local OpenStreetMap extract
// (tmp/energylandia.osm, ODbL).

export const ZONES = Object.freeze({
  "sweet-valley": Object.freeze({ id: "sweet-valley", name: "Sweet Valley", routeOrder: 0 }),
  aqualantis: Object.freeze({ id: "aqualantis", name: "Aqualantis", routeOrder: 1 }),
  "dragon-zone": Object.freeze({ id: "dragon-zone", name: "Smoczy Gród", routeOrder: 2 }),
  "extreme-zone": Object.freeze({ id: "extreme-zone", name: "Strefa Ekstremalna", routeOrder: 3 }),
  "family-zone": Object.freeze({ id: "family-zone", name: "Strefa Familijna", routeOrder: 4 }),
  fairyland: Object.freeze({ id: "fairyland", name: "Bajkolandia", routeOrder: 5 }),
});

export const DEFAULT_ZONE_ORDER = Object.freeze([
  "sweet-valley",
  "aqualantis",
  "dragon-zone",
  "extreme-zone",
  "family-zone",
  "fairyland",
]);

export const RULES_SOURCE_URL =
  "https://energylandia.pl/wp-content/uploads/2024/06/MAPKA_PL_2026.pdf";
export const OSM_SOURCE_URL = "https://www.openstreetmap.org/copyright";

const official = (path) => `https://energylandia.pl/atrakcje/${path}/`;

function attraction({
  restrictions,
  queueAliases = [],
  defaultStatus = "open",
  ...details
}) {
  const normalizedRestrictions = Object.freeze({
    minHeightWithGuardian: null,
    minAgeWithGuardian: null,
    maxAgeWithGuardian: null,
    soloHeight: null,
    maxHeight: null,
    ...restrictions,
  });

  return Object.freeze({
    ...details,
    lat: details.location.lat,
    lon: details.location.lon,
    defaultStatus,
    queueAliases: Object.freeze([details.name, ...queueAliases]),
    restrictions: normalizedRestrictions,
    // Mirrored fields make simple React filters convenient while the nested
    // object remains the canonical restriction model.
    ...normalizedRestrictions,
    sources: Object.freeze({
      restrictions: details.sourceUrl,
      coordinates: OSM_SOURCE_URL,
    }),
  });
}

export const ATTRACTIONS = Object.freeze([
  attraction({
    id: "honey-harbour",
    name: "Honey Harbour",
    osmId: "node/13049474740",
    zone: "sweet-valley",
    location: Object.freeze({ lat: 49.999015, lon: 19.4027344 }),
    restrictions: { minHeightWithGuardian: 100, soloHeight: 120 },
    routeOrder: 10,
    priority: 100,
    intensity: "medium",
    wet: false,
    durationMinutes: 3,
    queueAliases: ["Nacomi Honey Harbour", "Honey Harbor", "Honey Harbour 224"],
    sourceUrl: official("sweet-valley/honey-harbour"),
  }),
  attraction({
    id: "candy-carousel",
    name: "Candy Carousel",
    osmId: "node/13049474744",
    zone: "sweet-valley",
    location: Object.freeze({ lat: 49.9994225, lon: 19.402677 }),
    restrictions: { minAgeWithGuardian: 0, maxAgeWithGuardian: 13, soloHeight: 120 },
    routeOrder: 20,
    priority: 45,
    intensity: "calm",
    toddlerLike: true,
    resetStop: true,
    wet: false,
    durationMinutes: 4,
    queueAliases: ["Candy Carousel 217"],
    sourceUrl: official("sweet-valley/candy-carousel"),
  }),
  attraction({
    id: "choco-chip-creek",
    name: "Choco Chip Creek",
    osmId: "node/13049474738",
    zone: "sweet-valley",
    location: Object.freeze({ lat: 50.0001719, lon: 19.4028551 }),
    restrictions: { minHeightWithGuardian: 120, soloHeight: 140 },
    routeOrder: 30,
    priority: 96,
    intensity: "medium",
    wet: false,
    durationMinutes: 5,
    queueAliases: ["Fluff Choco Chip Creek", "Choco Chip Creek 215"],
    sourceUrl: official("sweet-valley/choco-chip-creek"),
  }),
  attraction({
    id: "abyssus",
    name: "Abyssus",
    osmId: "node/8889371834",
    zone: "aqualantis",
    location: Object.freeze({ lat: 49.999943, lon: 19.4003237 }),
    restrictions: { minHeightWithGuardian: 120, soloHeight: 140 },
    routeOrder: 35,
    priority: 120,
    intensity: "high",
    wet: false,
    durationMinutes: 4,
    queueAliases: ["Abyssus"],
    sourceUrl: official("aqualantis/abyssus"),
  }),
  attraction({
    id: "light-explorers",
    name: "EKIPA Light Explorers",
    osmId: "node/8931281684",
    zone: "aqualantis",
    location: Object.freeze({ lat: 50.0007758, lon: 19.4009843 }),
    restrictions: { minHeightWithGuardian: 100, soloHeight: 120 },
    routeOrder: 40,
    priority: 98,
    intensity: "medium",
    wet: false,
    durationMinutes: 3,
    queueAliases: ["Light Explorers", "Ekipa Light Explorers", "Light Explorers 182"],
    sourceUrl: official("aqualantis/ekipa-light-explorers"),
  }),
  attraction({
    id: "stormy-ship",
    name: "Stormy Ship",
    osmId: "node/13055249781",
    zone: "aqualantis",
    location: Object.freeze({ lat: 50.0009253, lon: 19.4000986 }),
    restrictions: { minHeightWithGuardian: 110, soloHeight: 140 },
    routeOrder: 50,
    priority: 72,
    intensity: "medium",
    wet: false,
    durationMinutes: 4,
    queueAliases: ["Stormy Ship 178"],
    sourceUrl: official("aqualantis/stormy-ship"),
  }),
  attraction({
    id: "grotto-expedition",
    name: "Grotto Expedition",
    osmId: "way/1137535667",
    zone: "aqualantis",
    location: Object.freeze({ lat: 50.0007743, lon: 19.4005611 }),
    restrictions: { minAgeWithGuardian: 2, maxAgeWithGuardian: 13, soloHeight: 120 },
    routeOrder: 60,
    priority: 68,
    intensity: "calm",
    resetStop: true,
    wet: true,
    durationMinutes: 7,
    queueAliases: ["Grotto Expedition 181"],
    sourceUrl: official("aqualantis/grotto-expedition"),
  }),
  attraction({
    id: "frida",
    name: "Frida",
    osmId: "way/1429834443",
    zone: "dragon-zone",
    // Entrance/station area; the full track centroid lies farther north.
    location: Object.freeze({ lat: 50.0019266, lon: 19.4009519 }),
    restrictions: { minHeightWithGuardian: 100, soloHeight: 120 },
    routeOrder: 70,
    priority: 94,
    intensity: "medium",
    wet: false,
    durationMinutes: 3,
    queueAliases: ["Frida 157", "Frida Coaster"],
    sourceUrl: official("smoczy-grod/frida"),
  }),
  attraction({
    id: "wonder-wheel",
    name: "Wonder Wheel",
    osmId: "way/1307071301",
    zone: "dragon-zone",
    location: Object.freeze({ lat: 50.0012497, lon: 19.403917 }),
    restrictions: { minAgeWithGuardian: 0, maxAgeWithGuardian: 13, soloHeight: 120 },
    routeOrder: 80,
    priority: 58,
    intensity: "calm",
    resetStop: true,
    wet: false,
    durationMinutes: 10,
    queueAliases: ["Wonder Wheel 208"],
    sourceUrl: official("smoczy-grod/wonder-wheel"),
  }),
  attraction({
    id: "formula",
    name: "Formuła",
    osmId: "node/7338922202",
    zone: "extreme-zone",
    location: Object.freeze({ lat: 49.9995868, lon: 19.4056038 }),
    restrictions: { minHeightWithGuardian: 120, soloHeight: 140 },
    routeOrder: 85,
    priority: 116,
    intensity: "high",
    wet: false,
    durationMinutes: 3,
    queueAliases: ["Moya Formula Rc", "Formula Rc", "Formuła"],
    sourceUrl: official("strefa-ekstremalna/formula-roller-coaster"),
  }),
  attraction({
    id: "anaconda",
    name: "Anaconda",
    osmId: "way/666524712",
    zone: "family-zone",
    location: Object.freeze({ lat: 50.0004916, lon: 19.4055219 }),
    restrictions: { minHeightWithGuardian: 120, soloHeight: 140 },
    routeOrder: 85,
    priority: 112,
    intensity: "high",
    wet: true,
    durationMinutes: 5,
    queueAliases: ["Anaconda", "Fast Pass Anaconda"],
    sourceUrl: official("strefa-familijna/anaconda"),
  }),
  attraction({
    id: "rmf-dragon",
    name: "RMF Dragon",
    osmId: "node/7338922201",
    zone: "family-zone",
    location: Object.freeze({ lat: 49.9999609, lon: 19.4063934 }),
    restrictions: { minHeightWithGuardian: 120, soloHeight: 130 },
    routeOrder: 90,
    priority: 96,
    intensity: "high",
    wet: false,
    durationMinutes: 3,
    queueAliases: ["Dragon RMF", "RMF Dragon Roller Coaster", "RMF Dragon 34"],
    sourceUrl: official("strefa-familijna/rmf-dragon-roller-coaster"),
  }),
  attraction({
    id: "monster-house",
    name: "Monster House",
    osmId: "way/371626338",
    zone: "family-zone",
    location: Object.freeze({ lat: 50.000455, lon: 19.4076313 }),
    restrictions: { minAgeWithGuardian: 4, maxAgeWithGuardian: 12, soloHeight: 130 },
    routeOrder: 100,
    priority: 72,
    intensity: "medium",
    indoor: true,
    wet: false,
    durationMinutes: 6,
    queueAliases: ["Monster Attack", "Monster Atack", "Monster House 36"],
    sourceUrl: official("strefa-familijna/monster-atack"),
  }),
  attraction({
    id: "atlantis",
    name: "Atlantis",
    osmId: "way/406283306",
    zone: "family-zone",
    location: Object.freeze({ lat: 50.001078, lon: 19.4077093 }),
    restrictions: { minAgeWithGuardian: 4, maxAgeWithGuardian: 12, soloHeight: 140 },
    routeOrder: 110,
    priority: 76,
    intensity: "medium",
    wet: true,
    durationMinutes: 8,
    queueAliases: ["Atlantis 42", "Atlantis Spływ"],
    sourceUrl: official("strefa-familijna/atlantis"),
  }),
  attraction({
    id: "boomerang",
    name: "Boomerang",
    osmId: "node/13051588693",
    zone: "family-zone",
    location: Object.freeze({ lat: 50.0014148, lon: 19.4081113 }),
    restrictions: { minHeightWithGuardian: 100, soloHeight: 120 },
    routeOrder: 120,
    priority: 100,
    intensity: "medium",
    wet: false,
    durationMinutes: 3,
    queueAliases: ["Boomerang 98", "Boomerang Roller Coaster"],
    sourceUrl: official("strefa-familijna/boomerang"),
  }),
  attraction({
    id: "splash-battle",
    name: "Splash Battle",
    osmId: "way/793967921",
    zone: "family-zone",
    location: Object.freeze({ lat: 50.0008146, lon: 19.4098557 }),
    restrictions: { minAgeWithGuardian: 4, maxAgeWithGuardian: 12, soloHeight: 120 },
    routeOrder: 130,
    priority: 78,
    intensity: "medium",
    wet: true,
    durationMinutes: 7,
    queueAliases: ["Splash Battle 41"],
    sourceUrl: official("strefa-familijna/splash-battle"),
  }),
  attraction({
    id: "gold-mine",
    name: "Toffifee Kopalnia Złota",
    osmId: "way/371626337",
    zone: "family-zone",
    location: Object.freeze({ lat: 50.0005127, lon: 19.4099449 }),
    restrictions: { minAgeWithGuardian: 6, maxAgeWithGuardian: 13, soloHeight: 140 },
    routeOrder: 140,
    priority: 84,
    intensity: "medium",
    wet: true,
    durationMinutes: 5,
    queueAliases: ["Kopalnia Złota", "Toffifee", "Gold Mine", "Kopalnia Złota 40"],
    sourceUrl: official("strefa-familijna/kopalnia-zlota"),
  }),
  attraction({
    id: "energus",
    name: "Śmiejżelki Energuś",
    osmId: "node/7338922200",
    zone: "fairyland",
    location: Object.freeze({ lat: 50.0004324, lon: 19.4106295 }),
    restrictions: { minHeightWithGuardian: 100, soloHeight: 120 },
    routeOrder: 150,
    priority: 82,
    intensity: "medium",
    wet: false,
    durationMinutes: 3,
    queueAliases: ["Energuś", "Energus", "Śmiejżelka Energuś", "Energuś 23"],
    sourceUrl: official("bajkolandia/energus-roller-coaster"),
  }),
  attraction({
    id: "jungle-adventure",
    name: "Jungle Adventure",
    osmId: "node/13051588683",
    zone: "family-zone",
    location: Object.freeze({ lat: 49.9985728, lon: 19.4084088 }),
    restrictions: { minHeightWithGuardian: 120, soloHeight: 140, maxHeight: 195 },
    routeOrder: 160,
    priority: 88,
    intensity: "high",
    wet: true,
    durationMinutes: 8,
    queueAliases: ["Jungle Adventure 96", "Jungle"],
    sourceUrl: official("strefa-familijna/jungle-adventure"),
  }),
]);

function toilet(id, name, lat, lon, osmId, extra = {}) {
  return Object.freeze({
    id,
    name,
    lat,
    lon,
    location: Object.freeze({ lat, lon }),
    osmId,
    sourceUrl: OSM_SOURCE_URL,
    ...extra,
  });
}

// Toilets nearest to the curated west-to-east route. OSM has no mapped toilet
// inside Sweet Valley itself; the Aqualantis and Smoczy Gród points are the
// nearest verified options from that part of the park.
export const TOILETS = Object.freeze([
  toilet(
    "toilet-aqualantis",
    "Toaleta Aqualantis",
    50.0009856,
    19.3999922,
    "node/11071728021",
    { access: "customers" },
  ),
  toilet(
    "toilet-dragon-zone",
    "Toaleta Smoczy Gród",
    50.0018812,
    19.4017297,
    "node/9865905017",
    { access: "customers", fee: false },
  ),
  toilet(
    "toilet-formula-tunnel",
    "Toaleta przy tunelu / Formule",
    50.0003247,
    19.4048581,
    "node/13137128810",
    { access: "customers", fee: false },
  ),
  toilet(
    "toilet-family-central",
    "Toaleta Strefa Familijna — centrum",
    49.9997386,
    19.4072007,
    "way/794236877",
  ),
  toilet(
    "toilet-family-east",
    "Toaleta przy Splash Battle",
    50.0002744,
    19.4095514,
    "node/11070961904",
    { access: "customers" },
  ),
  toilet(
    "toilet-family-south",
    "Toaleta przy Jungle Adventure",
    49.9983889,
    19.4087961,
    "node/13137128888",
    { access: "customers", fee: false },
  ),
]);

export const ATTRACTIONS_BY_ID = Object.freeze(
  Object.fromEntries(ATTRACTIONS.map((item) => [item.id, item])),
);

export const TOILETS_BY_ID = Object.freeze(
  Object.fromEntries(TOILETS.map((item) => [item.id, item])),
);
